[FIDUCIAL VALUES]
H0 = 67.0
omega_b = 0.049
omega_cdm = 0.27
n_s = 0.96
ln10^{10}a_s = 3.0445
a_ia = 0.16
eta_ia = 1.66
b_g1 = 1.33291
b_g2 = -0.72414 
b_g3 = 1.01830
b_g4 = -0.14913 
b_mag1 = 0.00
b_mag2 = 0.0
b_mag3 = 0.0
b_mag4 = 0.0
b_mag5 = 0.0
b_mag6 = 0.0
b_mag7 = 0.0
b_mag8 = 0.0
b_mag9 = 0.0
b_mag10 = 0.0
b_mag11 = 0.0
b_mag12 = 0.0
b_mag13 = 0.0
m_1 = 0.000
m_2 = 0.000
m_3 = 0.000
m_4 = 0.000
m_5 = 0.000
m_6 = 0.000
m_7 = 0.000
m_8 = 0.000
m_9 = 0.000
m_10 = 0.000
m_11 = 0.0
m_12 = 0.0
m_13 = 0.0
D_1 = 0.000
D_2 = 0.000
D_3 = 0.000
D_4 = 0.000
D_5 = 0.000
D_6 = 0.000
D_7 = 0.000
D_8 = 0.000
D_9 = 0.000
D_10 = 0.000
D_11 = 0.0
D_12 = 0.0
D_13 = 0.0


[FINV]
N_pars = 50
N_nuisance = 45
run_fisher = False
finv_file = /home/awernersson/projects/playground/tutorials/observables/Fisher/Finv_LCDM_with_cloelib_corrected.npy
#finv_file = /home/awernersson/projects/merlin/Aux_files/Finv_genobs.npy
Nbin_z = 13
N_ell = 32
covmat = /home/awernersson/projects/playground/tutorials/observables/covariance_Gauss_13245_2D_format_probe_zpair_scale.npz
nz_example = /home/awernersson/projects/playground/tutorials/observables/nzTabSPV3_euclidlib_format.fits

[OBSERVATION]
OBS = /gpfs/scratch1/shared/awernersson/swyft_cloelib/obs_merlin_oldFinv.npy
OBS_CHOLESKY = /gpfs/scratch1/shared/awernersson/swyft_cloelib/obs_chol_merlin_oldFinv.npy
OBS_CHOLESKY_NOISELESS = /gpfs/scratch1/shared/awernersson/swyft_cloelib/obs_chol_noiseless_merlin_oldFinv.npy
LFID = /gpfs/scratch1/shared/awernersson/swyft_cloelib/Lfid_merlin_oldFinv.npy
metadata_path = /gpfs/scratch1/shared/awernersson/swyft_cloelib/obs_metadata_merlin_oldFinv.npz

[AUX FILES]
#SVD = /home/awernersson/projects/playground/tutorials/observables/Aux_files/SVD_LCDM_merlin_newFinv.npy
#OBS = /gpfs/scratch1/shared/awernersson/swyft_cloelib/obs_3x2pt_LCDM_merlin.npy
#LFID = /gpfs/scratch1/shared/awernersson/swyft_cloelib/cholesky_3x2pt_LCDM_merlin.npy
covmat = /home/awernersson/projects/playground/tutorials/observables/covariance_Gauss_13245_2D_format_probe_zpair_scale.npz
nz_example = /home/awernersson/projects/playground/tutorials/observables/nzTabSPV3_euclidlib_format.fits
ell_file = /home/awernersson/projects/merlin/Aux_files/ell_theory.npy
zmean_file = /home/awernersson/projects/merlin/Aux_files/zmean_dr3.npy

[PCA]
store_pca = True
SVD = /home/awernersson/projects/playground/tutorials/observables/Aux_files/SVD_LCDM_merlin_oldFinve-3.npy
q = 500
variance_cut = 0.001

[STORES]
checkpoint_path = /gpfs/scratch1/shared/awernersson/Euclid_Swyft/checkpoint_paths/ssfiles_train75_cosmo_test_oldFinve-2
predictions_cosmo = /gpfs/scratch1/shared/awernersson/swyft_cloelib/predictions/merlin_cosmo_predictions_20April_oldFinve-3.pkl
predictions_nuisance = /gpfs/scratch1/shared/awernersson/Euclid_Swyft/predictions/nuisance_predictions_37param_75k_PCA75k1e-4_4Novstore.pkl
coverage_plot = /gpfs/scratch1/shared/awernersson/swyft_cloelib/predictions/coverage_cosmo.pdf

[SIMULATION]
store_path = /gpfs/scratch1/shared/awernersson/swyft_cloelib/Store_3x2pt_LCDM_100k_merlin_16A
N_sims = 100000
batch_size = 64
chunk_size = 64
n_workers = 36

[TRAINING]
learning_rate = 5e-4
batch_size = 256
num_workers = 12
max_epochs = 150
early_stopping = 20
train_fraction = 0.8
val_fraction = 0.2
precision = 64
coverage_test = True

[DEVICE PARAMS]
device = gpu
n_devices = 1
